from . import common
from . import test_cart_crud
from . import test_clasificador
from . import test_prompt_carrito
from . import test_endpoint
from . import test_modo_carrito
from . import test_numero_agregar
from . import test_recibo_pago
from . import test_imagenes_catalogo
from . import test_catalogo_escalable
from . import test_botones_carrito