from . import common
from . import test_cart_crud
from . import test_clasificador
from . import test_prompt_carrito
from . import test_endpoint
from . import test_modo_carrito
from . import test_numero_agregar
from . import test_recibo_pago
from . import test_imagenes_catalogo
from . import test_catalogo_escalable
from . import test_botones_carrito
from . import test_enlace_tienda
from . import test_persistencia_modo
from . import test_mundo_carrito
from . import test_vendedor_ia
from . import test_captura_guiada
from . import test_ajuste_carrito
from . import test_spec55_salida_bienvenida
